micronaut:
  application:
    name: mnNonnullRelationFieldsPostgres
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
netty:
  default:
    allocator:
      max-order: 3
